import Head from "next/head";
type meta = {
  title: string;
  description: string;
};

export const Meta = ({ title, description }: meta) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

Meta.defaultProps = {
  title: "Welcome Home",
  description: "Generated by create next app",
};
