import Head from "next/head";
import styles from "../styles/Home.module.css";

import ArticlesList from "../components/ArticlesList";

export type articlesListType = {
  articles: [
    {
      userId: Number;
      id: Number;
      title: String;
      body: String;
    }
  ];
};

export default function Home({ articles }: articlesListType) {
  console.log(articles);

  return (
    <>
      <Head>
        <title>Welcome Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticlesList articles={articles} />
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=6`
  );
  const articles = await res.json();
  return {
    props: {
      articles,
    },
  };
};
